[workspace]
members = [
    "emulator",
    "target-wasm",
    "target-linux",
    "target-windows",
    "target-macos",
    "target-android",
    "target-ios",
    "target-qemu-x86_64",
    "target-qemu-arm64"
]
